version: '2'
services:

  node:
    image: node:onbuild
    volumes:
      - ./:/root/
    working_dir: /root/
    command: node app.js
    ports:
      - "80:3000"
    links:
      - mongo
    environment:
      MONGODB: "mongodb://mongo:27017/hackathon"

  mongo:
    image: mongo:2.6.11
    command: mongod --smallfiles

