version: '2'
services:

  web:
    image: mikemichel/hackathon-starter:0.1
    ports:
      - "80:3000"
    depends_on:
      - mongo
    networks:
      - all
    environment:
      MONGODB_URI: "mongodb://mongo:27017/hackathon"

  mongo:
    image: mongo:3
    command: mongod --smallfiles
    volumes:
      - /mnt/mongodb:/data/db
    networks:
      - all

networks:
  all:
